removed daterange_is_current added drop_procedure fixed employee_name to understand new employee table columns changed build_emp_comm to build_profit_item (whole new function) added parentheses around return from period_num

diff --git a/t3/timerweb/kshlib b/t3/timerweb/kshlib
--- a/t3/timerweb/kshlib
+++ b/t3/timerweb/kshlib
@@ -169,20 +169,6 @@ function bcp_file
 ###                           SQL utilities                              ###
 ############################################################################
 
-function daterange_is_current
-{
-	from=$1
-	to=$2
-
-	if [ -z "$from" -o -z "$to" ]
-	then
-		echo "daterange_is_current: missing argument" >&2
-		return
-	fi
-
-	echo "getdate() between $from and isnull($to, $END_OF_TIME)"
-}
-
 function make_midnight
 {
 	date=$1
@@ -264,6 +250,31 @@ function overwrite_table
 	END
 }
 
+function drop_procedure
+{
+	procedure=$1
+
+	if [ -z "$procedure" ]
+	then
+		echo "drop_procedure: missing argument" >&2
+		return
+	fi
+
+	cat <<-END
+
+		if exists
+		(
+			select 1
+			from sysobjects
+			where name = '$procedure'
+			and type = 'P'
+		)
+		drop procedure $procedure
+		go
+
+	END
+}
+
 function copy_structure
 {
 	from_table=$1
@@ -297,93 +308,177 @@ function copy_structure
 ###                     TIMER specific SQL utilities                     ###
 ############################################################################
 
-# gives the employee first name, with last initial if showlast is turned on
+# gives the employee first name, with last initial if show_last is turned on
 
 function employee_name
 {
 	table_alias=$1		# most commonly, "e"
 
-	echo "rtrim($table_alias.name) + ' ' + \c"
-	echo "substring($table_alias.lname, $table_alias.showlast, 1)"
+	echo "rtrim($table_alias.fname) + ' ' + \c"
+	echo "substring($table_alias.lname, $table_alias.show_last, 1)"
 }
 
-# builds the temp table necessary for the billing/payroll stored procedures,
-# then fills it up appropriately based on the SQL query it is given
-
-function build_emp_comm
+function build_profit_item
 {
-	log_where_clause="$1"
-	op_where_clause="$2"
-	tc_where_clause="$3"
+	# in the where clause, you should use "log" as the alias to refer
+	# to columns from the log table (which could be any of the three)
+	where_clause=$1
 
-	if [ -z "$log_where_clause" ]
+	if [ -z "$where_clause" ]
 	then
-		echo "build_emp_comm: missing argument" >&2
-		return
+		# do everything
+		where_clause="1 = 1"
 	fi
 
-	# if op and tc where clauses not specified, simply adjust for the 
-	# fact that not all of the tables use the same column name for "date"
-	if [ -z "$op_where_clause" ]
-	then
-		op_where_clause=$(echo "$log_where_clause" |
-				perl -pe 's/\bdate\b/date_delivered/')
-	fi
-	if [ -z "$tc_where_clause" ]
-	then
-		tc_where_clause=$(echo "$log_where_clause" |
-				perl -pe 's/\bdate\b/start_time/')
-	fi
+	# in order to handle projects which demand profit calculated at
+	# the end of the project, we'll have to substitute the project end
+	# date for any requests on the log date
+	# (if no requests on the log date were made, that's okay too)
+	end_profit_where_clause=$(echo $where_clause | perl -pe '
+			s/\blog\.date\b/p.end_date/g;
+	')
 
+	# note that we use the same alias (log) for all three of the log tables
+	# this enables our clients to refer to the columns no matter which
+	# of the three tables we're working on ... of course it also means
+	# that they may _not_ refer to a column which is not common to all three
 	cat <<-END
 
-		create table #emp_comm
-		(
-			id          numeric(6,0)    identity,   -- for the cursor
-			source_tbl	varchar(30)		NOT NULL,	-- source table name
-			source_id	numeric(6,0)	NULL,		-- id from source table
-			emp         char(3)         NOT NULL,   -- employee code
-			client      char(3)         NOT NULL,   -- client code
-			proj        char(3)         NOT NULL,   -- project code
-			date        datetime        NOT NULL,   -- date of work done
-			hours       numeric(6,2)    NOT NULL,   -- how many hours
-			payrate     money           NULL,       -- how much emp gets paid
-			paytype     char(1)         NULL,       -- employee or subcontr?
-			billrate    money           NULL,       -- billing rate per hour
-			bill_hours	numeric(6,2)	NULL,		-- hours adj by bill ratio
-			amt_billed  money           NULL,       -- total client was billed
-			salescomm   smallmoney      NULL,       -- total sales commission 
-			refcomm     smallmoney      NULL,       -- total referral commission
-			amt_paid    money           NULL,       -- total employee was paid
-			gross       money           NULL,       -- amt_billed - sales - ref
-			diff        money           NULL,       -- 'simple' profit
-			empcomm     money           NULL        -- total employee comm
-		)
+		set nocount on
+		go
 
-		insert #emp_comm
-		    (source_tbl, source_id, emp, client, proj, date, hours)
-		select 'log', id, emp, client, proj, date, hours
-		from log l
-		where $log_where_clause
+		-- clear out our profit items tables
+		delete time_log_profit
+		delete profit_item
 
-		insert #emp_comm
-			(source_tbl, emp, client, proj, date, hours, amt_billed, amt_paid)
-		select 'other_profits', '', client, '', date_delivered, 0,
-				amount_billed, amount_paid
-		from other_profits op
-		where $op_where_clause
+		-- for time logs, we'll need to fill the time_log_profit table
+		-- calc_total_price will later insert them into profit_item
+		-- note that we insert a default billing ratio of 1
+		-- (this could get overridden later by calc_total_price)
 
-		insert #emp_comm
-			(source_tbl, emp, client, proj, date, hours)
-		select 'training_class', '', client, proj, start_time,
-			$(round 'datediff(minute, start_time, end_time) / 60.0
-					- num_breaks * .25' .25 'U'
-			)
-		from training_class tc
-		where $tc_where_clause
+		-- first, get time logs that will be one profit item each
+		insert time_log_profit
+			(log_source, log_id, emp, client, proj, date, hours,
+					start_date, end_date, requires_payment,
+					resource_billing, class_billing, billing_ratio, sum_by_proj)
+		select log.log_source, log.log_id, log.emp, log.client, log.proj,
+				log.date, log.hours, log.date, log.date, pt.requires_payment,
+				pt.resource_billing, pt.class_billing, 1, 0
+		from time_log log, project p, project_type pt
+		where $where_clause
+		and log.client = p.client
+		and log.proj = p.proj
+		and log.date between p.start_date and p.end_date
+		and p.proj_type = pt.proj_type
+		and pt.requires_billing = 1
+		and pt.no_profit_till_end = 0
+
+		-- next, get time logs that will be summed
+		-- into one profit item per project
+		insert time_log_profit
+			(log_source, log_id, emp, client, proj, date, hours,
+					start_date, end_date, requires_payment,
+					resource_billing, class_billing, billing_ratio, sum_by_proj)
+		select log.log_source, log.log_id, log.emp, log.client, log.proj,
+				log.date, log.hours, p.start_date, p.end_date,
+				pt.requires_payment, pt.resource_billing,
+				pt.class_billing, 1, 1
+		from time_log log, project p, project_type pt
+		where $end_profit_where_clause
+		and log.client = p.client
+		and log.proj = p.proj
+		and log.date between p.start_date and p.end_date
+		and p.proj_type = pt.proj_type
+		and pt.requires_billing = 1
+		and pt.no_profit_till_end = 1
+
+		-- the remainder we can insert directly into profit_item ourselves
+
+		-- now insert relevant materials logs
+		-- (they're pretty easy, even though there's three "types" of them)
+		-- STEP 1: materials logs with no project
+		insert profit_item
+			(client, proj, start_date, end_date, log_source, log_id, units,
+					price_per_unit)
+		select client, proj, date, date, log_source, log_id, 1, amount_billed
+		from materials_log log
+		where $where_clause
+		and proj is null
+		-- STEP 2: materials logs for projects with "now" profit calculation
+		insert profit_item
+			(client, proj, start_date, end_date, log_source, log_id, units,
+					price_per_unit)
+		select log.client, log.proj, log.date, log.date,
+				log.log_source, log.log_id, 1, log.amount_billed
+		from materials_log log, project p, project_type pt
+		where $where_clause
+		and log.client = p.client
+		and log.proj = p.proj
+		and p.proj_type = pt.proj_type
+		and pt.requires_billing = 1
+		and pt.no_profit_till_end = 0
+		-- STEP 3: materials logs for projects with "at end" profit calculation
+		insert profit_item
+			(client, proj, start_date, end_date, log_source, log_id, units,
+					price_per_unit)
+		select log.client, log.proj, log.date, log.date,
+				log.log_source, log.log_id, 1, log.amount_billed
+		from materials_log log, project p, project_type pt
+		where $end_profit_where_clause
+		and log.client = p.client
+		and log.proj = p.proj
+		and p.proj_type = pt.proj_type
+		and pt.requires_billing = 1
+		and pt.no_profit_till_end = 1
+
+		-- get class logs that are one item per class
+		insert profit_item
+			(client, proj, start_date, end_date, log_source, units,
+					price_per_unit)
+		select log.client, log.proj, log.date, log.date, 'class_log',
+				datediff(minute, log.start_time, log.end_time) / 60.0
+						- (isnull(log.num_breaks, 0) * .25),
+				log.num_students * br.rate
+		from class_log log, project p, project_type pt, bill_rate br
+		where $where_clause
+		and log.client = p.client
+		and log.proj = p.proj
+		and log.date between p.start_date and p.end_date
+		and p.proj_type = pt.proj_type
+		and pt.requires_billing = 1
+		and pt.no_profit_till_end = 0
+		and log.client = br.client
+		and log.proj = br.proj
+		and log.date between br.start_date and br.end_date
+
+		-- get class logs that are "full project" quantities
+		insert profit_item
+			(client, proj, start_date, end_date, log_source, units,
+					price_per_unit)
+		select log.client, log.proj, p.start_date, p.end_date, 'class_log SUM',
+				1, sum((datediff(minute, log.start_time, log.end_time) / 60.0
+						- (isnull(log.num_breaks, 0) * .25))
+						* log.num_students * br.rate)
+		from class_log log, project p, project_type pt, bill_rate br
+		where $end_profit_where_clause
+		and log.client = p.client
+		and log.proj = p.proj
+		and p.proj_type = pt.proj_type
+		and pt.requires_billing = 1
+		and pt.no_profit_till_end = 1
+		and log.client = br.client
+		and log.proj = br.proj
+		and log.date between br.start_date and br.end_date
+		group by log.client, log.proj, p.start_date, p.end_date
+
+		go
+
+		set nocount off
+		go
 
 	END
 }
+
 
 # the period functions are designed to make it easy to figure out what
 # week (7-day period) you're in, and what the beginning of the week is, and
@@ -397,7 +492,7 @@ function period_num
 	date="$1"				# the date to find the period number for
 	period_len="$2"			# how many days a period is
 
-	echo "datediff(day, $BAREFOOT_EPOCH, $date) / $period_len"
+	echo "(datediff(day, $BAREFOOT_EPOCH, $date) / $period_len)"
 }
 
 function period_day
